"""GitHub Actions workflow templates for generated projects."""

from __future__ import annotations

from cppboot.generate.android import ANDROID_ABIS, EMULATOR_API_LEVEL
from cppboot.generate.context import Context

_Context = Context


def _android_aar_verify_lines(ctx: _Context, *, jni_and_headers: bool) -> str:
    """Shell fragment asserting the release AAR contains every ABI's library."""
    lines = [f"          for abi in {' '.join(ANDROID_ABIS)}; do"]
    lines.append(
        f'            grep -qx "prefab/modules/{ctx.target}/libs/'
        f'android.${{abi}}/lib{ctx.target}.so" aar-entries.txt'
    )
    if jni_and_headers:
        lines.append(f'            grep -qx "jni/${{abi}}/lib{ctx.target}.so" aar-entries.txt')
    lines.append("          done")
    if jni_and_headers:
        lines.append(
            f'          grep -qx "prefab/modules/{ctx.target}/include/'
            f'{ctx.namespace}/version.hpp" aar-entries.txt'
        )
    return "\n".join(lines)


def _github_actions_android_workflow(ctx: _Context) -> str:
    """Android Prefab AAR: Gradle build, AAR verification, emulator tests."""
    return f"""\
# Generated by cppboot (--with-android-ci)
# Android Prefab AAR: Gradle/AGP drives the CMake build (NDK auto-installed),
# the release AAR contents are verified, and the consumer test app runs the
# native test suite on an Android emulator.
name: Android

on:
  push:
  pull_request:

concurrency:
  group: ${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  android:
    name: Android (Prefab AAR / emulator)
    runs-on: ubuntu-latest
    timeout-minutes: 35

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Build Debug AAR and consumer APK
        run: |
          bash android/gradlew -p android --no-daemon :{ctx.target}:assembleDebug
          bash android/gradlew -p android --no-daemon :test-app:assembleDebug

      - name: Build Release AAR and consumer APK
        run: |
          bash android/gradlew -p android --no-daemon :{ctx.target}:assembleRelease
          bash android/gradlew -p android --no-daemon :test-app:assembleRelease

      - name: Verify Release AAR
        run: |
          set -euo pipefail
          aar=android/{ctx.target}/build/outputs/aar/{ctx.target}-release.aar
          test -f "${{aar}}"
          unzip -Z1 "${{aar}}" > aar-entries.txt
{_android_aar_verify_lines(ctx, jni_and_headers=True)}
          version="$(tr -d '[:space:]' < VERSION | sed 's/^v//;s/^V//;s/#.*//')"
          unzip -p "${{aar}}" prefab/prefab.json | grep -q "\\"version\\"[[:space:]]*:[[:space:]]*\\"${{version}}\\""

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Release package tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: {EMULATOR_API_LEVEL}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: bash scripts/run_android_tests.sh

      - name: Package Android Release AAR
        id: package
        run: |
          set -euo pipefail
          version="$(tr -d '[:space:]' < VERSION | sed 's/^v//;s/^V//;s/#.*//')"
          stem="{ctx.name}-android-release-${{version}}"
          mkdir -p dist
          cp android/{ctx.target}/build/outputs/aar/{ctx.target}-release.aar "dist/${{stem}}.aar"
          echo "artifact_name=${{stem}}" >> "${{GITHUB_OUTPUT}}"
          echo "artifact_path=dist/${{stem}}.aar" >> "${{GITHUB_OUTPUT}}"

      - name: Upload Android package
        uses: actions/upload-artifact@v7
        with:
          name: ${{{{ steps.package.outputs.artifact_name }}}}
          path: ${{{{ steps.package.outputs.artifact_path }}}}
          if-no-files-found: error
          retention-days: 14
"""


def _github_actions_workflow(ctx: _Context) -> str:
    """Cross-platform CI: Linux/macOS/Windows × Debug+Release, test, bench."""
    modules_toolchain = ""
    if ctx.with_modules:
        modules_toolchain = """
      - name: Install module-capable C++ toolchain (Linux)
        if: runner.os == 'Linux'
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y g++-14
          echo "CC=gcc-14" >> "${GITHUB_ENV}"
          echo "CXX=g++-14" >> "${GITHUB_ENV}"

      - name: Install module-capable C++ toolchain (macOS)
        if: runner.os == 'macOS'
        run: |
          set -euo pipefail
          brew install llvm
          echo "CC=$(brew --prefix llvm)/bin/clang" >> "${GITHUB_ENV}"
          echo "CXX=$(brew --prefix llvm)/bin/clang++" >> "${GITHUB_ENV}"
"""
    return f"""\
# Generated by cppboot (default; --no-github-actions to skip)
# Matrix CI: Ubuntu, macOS, Windows — Debug + Release builds, tests, benchmarks.
# Action pins: latest stable majors (checkout/upload-artifact v7; get-cmake latest CMake/Ninja).
name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  build:
    name: ${{{{ matrix.os }}}}
    runs-on: ${{{{ matrix.os }}}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      APP_NAME: {ctx.name}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
{modules_toolchain}
      - name: Enable MSVC developer command prompt
        if: runner.os == 'Windows'
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Configure Debug
        run: >
          cmake -S . -B build/debug -G Ninja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build Debug
        run: cmake --build build/debug --parallel

      - name: Test Debug
        run: ctest --test-dir build/debug --output-on-failure --parallel

      - name: Configure Release
        run: >
          cmake -S . -B build/release -G Ninja
          -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: cmake --build build/release --parallel

      - name: Test Release
        run: ctest --test-dir build/release --output-on-failure --parallel

      - name: Benchmark (Release)
        run: |
          set -euo pipefail
          # Collect Google Benchmark binaries (none is OK).
          bins="$(find build/release -type f \\( -name '*bench' -o -name '*_bench' -o -name '*bench.exe' -o -name '*_bench.exe' \\) 2>/dev/null | head -n 20 || true)"
          if [ -z "${{bins}}" ]; then
            echo "No benchmark binaries found; skipping."
            exit 0
          fi
          while IFS= read -r bin; do
            [ -z "${{bin}}" ] && continue
            # Skip non-executables if any slip through on Windows.
            if [ ! -x "${{bin}}" ] && [[ "${{bin}}" != *.exe ]]; then
              continue
            fi
            echo "Running ${{bin}}"
            "${{bin}}" --benchmark_min_time=0.01s
          done <<< "${{bins}}"

      # Archives: <app>-<os>-<arch>-<debug|release>-<version>.zip
      - name: Package Debug artifacts
        id: pkg_debug
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import os, re, shutil, subprocess
          from pathlib import Path

          app = os.environ["APP_NAME"]
          os_name = {{"Linux": "linux", "macOS": "macos", "Windows": "windows"}}.get(
              os.environ.get("RUNNER_OS", ""), os.environ.get("RUNNER_OS", "unknown").lower()
          )
          arch = {{"X64": "x86_64", "ARM64": "arm64", "X86": "x86"}}.get(
              os.environ.get("RUNNER_ARCH", ""), os.environ.get("RUNNER_ARCH", "unknown").lower()
          )
          config = "debug"
          bin_dir = Path("build") / config / "bin"
          version = "0.1.0"
          for candidate in (bin_dir / app, bin_dir / f"{{app}}.exe"):
              if candidate.is_file():
                  try:
                      out = subprocess.check_output([str(candidate), "--version"], text=True, stderr=subprocess.STDOUT)
                      m = re.search(r"\\d+\\.\\d+\\.\\d+", out)
                      if m:
                          version = m.group(0)
                  except Exception:
                      pass
                  break
          stem = f"{{app}}-{{os_name}}-{{arch}}-{{config}}-{{version}}"
          staging = Path("dist") / stem
          if staging.exists():
              shutil.rmtree(staging)
          staging.mkdir(parents=True)
          if bin_dir.is_dir():
              for p in bin_dir.iterdir():
                  dest = staging / p.name
                  if p.is_file():
                      shutil.copy2(p, dest)
                  elif p.is_dir():
                      shutil.copytree(p, dest)
          archive = shutil.make_archive(str(Path("dist") / stem), "zip", root_dir="dist", base_dir=stem)
          print(f"Created {{archive}}")
          with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as fh:
              fh.write(f"artifact_name={{stem}}\\n")
              fh.write(f"artifact_path={{archive}}\\n")
          PY

      - name: Upload Debug artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{{{ steps.pkg_debug.outputs.artifact_name }}}}
          path: ${{{{ steps.pkg_debug.outputs.artifact_path }}}}
          if-no-files-found: error
          retention-days: 14

      - name: Package Release artifacts
        id: pkg_release
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import os, re, shutil, subprocess
          from pathlib import Path

          app = os.environ["APP_NAME"]
          os_name = {{"Linux": "linux", "macOS": "macos", "Windows": "windows"}}.get(
              os.environ.get("RUNNER_OS", ""), os.environ.get("RUNNER_OS", "unknown").lower()
          )
          arch = {{"X64": "x86_64", "ARM64": "arm64", "X86": "x86"}}.get(
              os.environ.get("RUNNER_ARCH", ""), os.environ.get("RUNNER_ARCH", "unknown").lower()
          )
          config = "release"
          bin_dir = Path("build") / config / "bin"
          version = "0.1.0"
          for candidate in (bin_dir / app, bin_dir / f"{{app}}.exe"):
              if candidate.is_file():
                  try:
                      out = subprocess.check_output([str(candidate), "--version"], text=True, stderr=subprocess.STDOUT)
                      m = re.search(r"\\d+\\.\\d+\\.\\d+", out)
                      if m:
                          version = m.group(0)
                  except Exception:
                      pass
                  break
          stem = f"{{app}}-{{os_name}}-{{arch}}-{{config}}-{{version}}"
          staging = Path("dist") / stem
          if staging.exists():
              shutil.rmtree(staging)
          staging.mkdir(parents=True)
          if bin_dir.is_dir():
              for p in bin_dir.iterdir():
                  dest = staging / p.name
                  if p.is_file():
                      shutil.copy2(p, dest)
                  elif p.is_dir():
                      shutil.copytree(p, dest)
          archive = shutil.make_archive(str(Path("dist") / stem), "zip", root_dir="dist", base_dir=stem)
          print(f"Created {{archive}}")
          with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as fh:
              fh.write(f"artifact_name={{stem}}\\n")
              fh.write(f"artifact_path={{archive}}\\n")
          PY

      - name: Upload Release artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{{{ steps.pkg_release.outputs.artifact_name }}}}
          path: ${{{{ steps.pkg_release.outputs.artifact_path }}}}
          if-no-files-found: error
          retention-days: 14
"""


def _github_actions_sanitizers_workflow(ctx: _Context) -> str:
    """Linux ASan+UBSan build and test; failures fail the job."""
    return f"""\
# Generated by cppboot (default; --no-github-actions to skip)
# Linux AddressSanitizer + UndefinedBehaviorSanitizer: build and run unit tests.
# Sanitizer errors abort the process so the job fails.
name: Sanitizers

on:
  push:
  pull_request:

concurrency:
  group: ${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  asan-ubsan:
    name: ASan+UBSan (ubuntu-latest)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: Configure (sanitizers)
        run: >
          cmake -S . -B build/sanitizer -G Ninja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -D{ctx.macro}_ENABLE_SANITIZERS=ON

      - name: Build
        run: cmake --build build/sanitizer --parallel

      - name: Test under ASan+UBSan
        env:
          ASAN_OPTIONS: halt_on_error=1:abort_on_error=1:detect_leaks=1:detect_stack_use_after_return=1
          UBSAN_OPTIONS: halt_on_error=1:print_stacktrace=1
        run: ctest --test-dir build/sanitizer --output-on-failure --parallel

      - name: Smoke run app under sanitizers
        env:
          ASAN_OPTIONS: halt_on_error=1:abort_on_error=1:detect_leaks=1
          UBSAN_OPTIONS: halt_on_error=1:print_stacktrace=1
        run: |
          set -euo pipefail
          bin="build/sanitizer/bin/{ctx.name}"
          if [ ! -x "${{bin}}" ]; then
            echo "app binary not found at ${{bin}}"
            exit 1
          fi
          "${{bin}}" --version
"""


def _github_actions_release_workflow(ctx: _Context) -> str:
    """Tag / dispatch release: matrix Release builds, notes, zip assets."""
    android_job = ""
    publish_needs = "[prepare, build]"
    assets_find = "-name '*.zip'"
    release_files = "release-assets/**/*.zip"
    if ctx.with_android_ci:
        publish_needs = "[prepare, build, build-android]"
        assets_find = "\\( -name '*.zip' -o -name '*.aar' \\)"
        release_files = """|
            release-assets/**/*.zip
            release-assets/**/*.aar"""
        android_job = f"""
  build-android:
    name: build-android (Prefab AAR / emulator)
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 35
    env:
      RELEASE_VERSION: ${{{{ needs.prepare.outputs.version }}}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Build Release AAR and consumer APK
        run: |
          bash android/gradlew -p android --no-daemon :{ctx.target}:assembleRelease
          bash android/gradlew -p android --no-daemon :test-app:assembleRelease

      - name: Verify Release AAR version and ABIs
        run: |
          set -euo pipefail
          aar=android/{ctx.target}/build/outputs/aar/{ctx.target}-release.aar
          test -f "${{aar}}"
          unzip -Z1 "${{aar}}" > aar-entries.txt
{_android_aar_verify_lines(ctx, jni_and_headers=False)}
          unzip -p "${{aar}}" prefab/prefab.json | grep -q "\\"version\\"[[:space:]]*:[[:space:]]*\\"${{RELEASE_VERSION}}\\""

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Release package tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: {EMULATOR_API_LEVEL}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: bash scripts/run_android_tests.sh

      - name: Stage Android Release AAR
        id: pkg
        run: |
          set -euo pipefail
          stem="{ctx.name}-android-release-${{RELEASE_VERSION}}"
          mkdir -p dist
          cp android/{ctx.target}/build/outputs/aar/{ctx.target}-release.aar "dist/${{stem}}.aar"
          echo "artifact_name=${{stem}}" >> "${{GITHUB_OUTPUT}}"
          echo "artifact_path=dist/${{stem}}.aar" >> "${{GITHUB_OUTPUT}}"

      - name: Upload Android Release AAR
        uses: actions/upload-artifact@v7
        with:
          name: ${{{{ steps.pkg.outputs.artifact_name }}}}
          path: ${{{{ steps.pkg.outputs.artifact_path }}}}
          if-no-files-found: error
          retention-days: 14
"""
    return f"""\
# Generated by cppboot (default; --no-github-actions to skip)
# Create GitHub Releases from v* tags or workflow_dispatch.
# Version source of truth is the root VERSION file (must match tag / input).
# Attaches <app>-<os>-<arch>-release-<version>.zip and auto-generated notes.
name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Semver without leading v (must match VERSION file; leave empty to use VERSION)"
        required: false
        type: string
        default: ""
      prerelease:
        description: "Mark as prerelease"
        required: false
        type: boolean
        default: false
      dry_run:
        description: "Build and draft only (do not publish release)"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

concurrency:
  group: release-${{{{ github.ref }}}}-${{{{ github.event_name }}}}
  cancel-in-progress: false

jobs:
  prepare:
    name: Resolve version
    runs-on: ubuntu-latest
    outputs:
      version: ${{{{ steps.meta.outputs.version }}}}
      tag: ${{{{ steps.meta.outputs.tag }}}}
      prerelease: ${{{{ steps.meta.outputs.prerelease }}}}
      dry_run: ${{{{ steps.meta.outputs.dry_run }}}}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Resolve tag and version (synced with VERSION file)
        id: meta
        env:
          INPUT_VERSION: ${{{{ github.event.inputs.version || '' }}}}
          INPUT_PRERELEASE: ${{{{ github.event.inputs.prerelease || 'false' }}}}
          INPUT_DRY_RUN: ${{{{ github.event.inputs.dry_run || 'false' }}}}
        run: |
          set -euo pipefail
          if [ ! -f VERSION ]; then
            echo "Missing VERSION file at repo root (single source of truth)."
            exit 1
          fi
          FILE_VERSION="$(tr -d '[:space:]' < VERSION | sed 's/^v//;s/^V//;s/#.*//')"
          if ! [[ "${{FILE_VERSION}}" =~ ^[0-9]+\\.[0-9]+\\.[0-9]+([.-].*)?$ ]]; then
            echo "Invalid VERSION file contents: '${{FILE_VERSION}}' (expected semver like 1.0.0)"
            exit 1
          fi

          if [ "${{{{ github.event_name }}}}" = "workflow_dispatch" ]; then
            if [ -z "${{INPUT_VERSION}}" ]; then
              VERSION="${{FILE_VERSION}}"
            else
              VERSION="${{INPUT_VERSION#v}}"
              VERSION="${{VERSION#V}}"
            fi
            if [ "${{VERSION}}" != "${{FILE_VERSION}}" ]; then
              echo "Release version '${{VERSION}}' does not match VERSION file '${{FILE_VERSION}}'."
              echo "Bump the VERSION file (and only that file), commit, then re-run the release."
              exit 1
            fi
            TAG="v${{VERSION}}"
            PRERELEASE="${{INPUT_PRERELEASE}}"
            DRY_RUN="${{INPUT_DRY_RUN}}"
            # Do not push tags here — that would re-trigger this workflow.
            # softprops/action-gh-release creates the tag on publish when missing.
          else
            TAG="${{{{ github.ref_name }}}}"
            VERSION="${{TAG#v}}"
            VERSION="${{VERSION#V}}"
            PRERELEASE=false
            DRY_RUN=false
            if [[ "${{TAG}}" == *-* ]] || [[ "${{TAG}}" == *alpha* ]] || [[ "${{TAG}}" == *beta* ]] || [[ "${{TAG}}" == *rc* ]]; then
              PRERELEASE=true
            fi
            if [ "${{VERSION}}" != "${{FILE_VERSION}}" ]; then
              echo "Tag version '${{VERSION}}' does not match VERSION file '${{FILE_VERSION}}'."
              echo "Bump VERSION, commit, then tag v${{FILE_VERSION}} (or retag after fixing VERSION)."
              exit 1
            fi
          fi
          {{
            echo "version=${{VERSION}}"
            echo "tag=${{TAG}}"
            echo "prerelease=${{PRERELEASE}}"
            echo "dry_run=${{DRY_RUN}}"
          }} >> "${{{{ github.output }}}}"
          echo "Resolved release ${{TAG}} (version=${{VERSION}}, file=${{FILE_VERSION}}, prerelease=${{PRERELEASE}}, dry_run=${{DRY_RUN}})"

  build:
    name: build-${{{{ matrix.os }}}}
    needs: prepare
    runs-on: ${{{{ matrix.os }}}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      APP_NAME: {ctx.name}
      RELEASE_VERSION: ${{{{ needs.prepare.outputs.version }}}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: Enable MSVC developer command prompt
        if: runner.os == 'Windows'
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Configure Release
        run: >
          cmake -S . -B build/release -G Ninja
          -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: cmake --build build/release --parallel

      - name: Test Release
        run: ctest --test-dir build/release --output-on-failure --parallel

      - name: Verify binary version matches release
        run: |
          set -euo pipefail
          bin="build/release/bin/${{APP_NAME}}"
          if [ ! -x "${{bin}}" ] && [ -f "${{bin}}.exe" ]; then
            bin="${{bin}}.exe"
          fi
          if [ ! -f "${{bin}}" ]; then
            echo "Missing app binary at build/release/bin/${{APP_NAME}}"
            exit 1
          fi
          out="$("${{bin}}" --version 2>&1 || true)"
          echo "Binary --version output: ${{out}}"
          if ! echo "${{out}}" | grep -Eq "(^|[[:space:]])${{RELEASE_VERSION}}([[:space:]]|$)"; then
            echo "Version mismatch: expected ${{RELEASE_VERSION}} from VERSION/tag, got: ${{out}}"
            echo "Edit the root VERSION file only, reconfigure/rebuild, then release."
            exit 1
          fi
          file_ver="$(tr -d '[:space:]' < VERSION | sed 's/^v//;s/^V//;s/#.*//')"
          if [ "${{file_ver}}" != "${{RELEASE_VERSION}}" ]; then
            echo "VERSION file (${{file_ver}}) drifted from release version (${{RELEASE_VERSION}})."
            exit 1
          fi

      - name: Package Release zip
        id: pkg
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import os, re, shutil, subprocess
          from pathlib import Path

          app = os.environ["APP_NAME"]
          version = os.environ["RELEASE_VERSION"]
          os_name = {{"Linux": "linux", "macOS": "macos", "Windows": "windows"}}.get(
              os.environ.get("RUNNER_OS", ""), os.environ.get("RUNNER_OS", "unknown").lower()
          )
          arch = {{"X64": "x86_64", "ARM64": "arm64", "X86": "x86"}}.get(
              os.environ.get("RUNNER_ARCH", ""), os.environ.get("RUNNER_ARCH", "unknown").lower()
          )
          config = "release"
          bin_dir = Path("build") / config / "bin"
          stem = f"{{app}}-{{os_name}}-{{arch}}-{{config}}-{{version}}"
          staging = Path("dist") / stem
          if staging.exists():
              shutil.rmtree(staging)
          staging.mkdir(parents=True)
          if not bin_dir.is_dir():
              raise SystemExit(f"missing {{bin_dir}}")
          for p in bin_dir.iterdir():
              dest = staging / p.name
              if p.is_file():
                  shutil.copy2(p, dest)
              elif p.is_dir():
                  shutil.copytree(p, dest)
          archive = shutil.make_archive(str(Path("dist") / stem), "zip", root_dir="dist", base_dir=stem)
          print(f"Created {{archive}}")
          with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as fh:
              fh.write(f"artifact_name={{stem}}\\n")
              fh.write(f"artifact_path={{archive}}\\n")
          PY

      - name: Upload Release zip (workflow artifact)
        uses: actions/upload-artifact@v7
        with:
          name: ${{{{ steps.pkg.outputs.artifact_name }}}}
          path: ${{{{ steps.pkg.outputs.artifact_path }}}}
          if-no-files-found: error
          retention-days: 14
{android_job}
  publish:
    name: Publish GitHub Release
    needs: {publish_needs}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download build zips
        uses: actions/download-artifact@v7
        with:
          path: release-assets
          pattern: "{ctx.name}-*"
          merge-multiple: true

      - name: List assets
        run: |
          set -euo pipefail
          find release-assets -type f {assets_find} | tee assets.list
          test -s assets.list

      - name: Create GitHub Release
        if: needs.prepare.outputs.dry_run != 'true'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{{{ needs.prepare.outputs.tag }}}}
          name: ${{{{ needs.prepare.outputs.tag }}}}
          generate_release_notes: true
          prerelease: ${{{{ needs.prepare.outputs.prerelease == 'true' }}}}
          files: {release_files}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}

      - name: Dry-run summary
        if: needs.prepare.outputs.dry_run == 'true'
        run: |
          echo "Dry run complete for ${{{{ needs.prepare.outputs.tag }}}} — assets:"
          find release-assets -type f {assets_find} -print
"""
