"""C++ source/test/benchmark templates and VERSION file."""

from __future__ import annotations

from cppboot.generate.context import Context

_Context = Context


def _version_file() -> str:
    """Single source of truth for package version (edit this file only)."""
    return "0.1.0\n"


def _version_header_in(ctx: _Context) -> str:
    """CMake configure_file template for the public version header."""
    _ = ctx
    return """\
#pragma once

#include <string_view>

/**
 * @file version.hpp
 * @brief Package version API (generated from VERSION + cmake/version.hpp.in).
 *
 * Do not edit this file by hand. Change the root VERSION file and reconfigure.
 */

namespace @PROJECT_NAMESPACE@ {

/// Semantic version major component.
inline constexpr int kVersionMajor = @PROJECT_VERSION_MAJOR@;
/// Semantic version minor component.
inline constexpr int kVersionMinor = @PROJECT_VERSION_MINOR@;
/// Semantic version patch component.
inline constexpr int kVersionPatch = @PROJECT_VERSION_PATCH@;

/**
 * @brief Returns the package version string (semantic version).
 * @return Version such as "0.1.0". Never empty.
 */
[[nodiscard]] std::string_view Version() noexcept;

}  // namespace @PROJECT_NAMESPACE@
"""


def _version_source_in(ctx: _Context) -> str:
    """CMake configure_file template for the version translation unit."""
    _ = ctx
    return """\
#include "@PROJECT_NAMESPACE@/version.hpp"

namespace @PROJECT_NAMESPACE@ {

std::string_view Version() noexcept {
  return "@PROJECT_VERSION_STRING@";
}

}  // namespace @PROJECT_NAMESPACE@
"""


def _version_module_in(ctx: _Context) -> str:
    """CMake configure_file template for the C++20 version module.

    Uses ``const char*`` (no standard-library includes) so the module interface
    stays free of global-module-fragment header pollution — friendlier to MSVC
    and mixed import/#include TUs.
    """
    return f"""\
/**
 * @file version.cppm
 * @brief C++20 module interface for the package version API (generated).
 *
 * Do not edit this file by hand. Change the root VERSION file and reconfigure.
 */

export module {ctx.namespace}.version;

/**
 * @brief Package version helpers for {ctx.name}.
 */
export namespace {ctx.namespace} {{

inline constexpr int kVersionMajor = @PROJECT_VERSION_MAJOR@;
inline constexpr int kVersionMinor = @PROJECT_VERSION_MINOR@;
inline constexpr int kVersionPatch = @PROJECT_VERSION_PATCH@;

/// Null-terminated semantic version string (static storage).
[[nodiscard]] const char* Version() noexcept;

}}  // namespace {ctx.namespace}

namespace {ctx.namespace} {{

const char* Version() noexcept {{
  return "@PROJECT_VERSION_STRING@";
}}

}}  // namespace {ctx.namespace}
"""


def _main_cpp(ctx: _Context) -> str:
    # MSVC modules: put classic #includes before import of project modules.
    if ctx.with_modules:
        prologue = f"""\
#include <CLI/CLI.hpp>

#include <iostream>
#include <string>

import {ctx.namespace}.version;
"""
    else:
        prologue = f"""\
#include "{ctx.namespace}/version.hpp"

#include <CLI/CLI.hpp>

#include <iostream>
#include <string>
"""
    return f"""\
/**
 * @file main.cpp
 * @brief Program entrypoint (always src/main.cpp in cppboot projects).
 *
 * Keep this file thin: parse args / wire dependencies, then call library code.
 */

{prologue}
/**
 * @brief Program entry.
 * @param argc Argument count.
 * @param argv Argument vector.
 * @return Exit status.
 */
int main(int argc, char** argv) {{
  CLI::App app{{"{ctx.name} — cppboot project"}};
  app.set_version_flag("-V,--version", std::string{{{ctx.namespace}::Version()}});
  CLI11_PARSE(app, argc, argv);

  std::cout << "{ctx.name} " << {ctx.namespace}::Version()
            << " — add components under src/ (see README.md / AGENTS.md)\\n";
  return 0;
}}
"""


def _version_test(ctx: _Context) -> str:
    if ctx.with_modules:
        includes = f"""\
#include <gtest/gtest.h>

#include <string>
#include <string_view>

import {ctx.namespace}.version;
"""
    else:
        includes = f"""\
#include "{ctx.namespace}/version.hpp"

#include <gtest/gtest.h>

#include <string>
#include <string_view>
"""
    return f"""\
/**
 * @file version_test.cpp
 * @brief Unit tests for {ctx.namespace}::Version.
 */

{includes}
namespace {{

TEST(VersionTest, IsNonEmpty) {{
  const std::string_view version = {ctx.namespace}::Version();
  EXPECT_FALSE(version.empty());
}}

TEST(VersionTest, MatchesComponentConstants) {{
  // Version() is generated from the root VERSION file; constants must agree.
  const std::string expected =
      std::to_string({ctx.namespace}::kVersionMajor) + "." +
      std::to_string({ctx.namespace}::kVersionMinor) + "." +
      std::to_string({ctx.namespace}::kVersionPatch);
  EXPECT_EQ(std::string_view{{{ctx.namespace}::Version()}}, expected);
  EXPECT_GE({ctx.namespace}::kVersionMajor, 0);
  EXPECT_GE({ctx.namespace}::kVersionMinor, 0);
  EXPECT_GE({ctx.namespace}::kVersionPatch, 0);
}}

TEST(VersionTest, HasThreeNumericComponents) {{
  const std::string_view version = {ctx.namespace}::Version();
  EXPECT_NE(version.find('.'), std::string_view::npos);
  EXPECT_NE(version.rfind('.'), std::string_view::npos);
  EXPECT_NE(version.find('.'), version.rfind('.'));
}}

}}  // namespace
"""


def _version_bench(ctx: _Context) -> str:
    if ctx.with_modules:
        includes = f"""\
#include <benchmark/benchmark.h>

#include <string_view>

import {ctx.namespace}.version;
"""
    else:
        includes = f"""\
#include "{ctx.namespace}/version.hpp"

#include <benchmark/benchmark.h>

#include <string_view>
"""
    return f"""\
/**
 * @file version_bench.cpp
 * @brief Microbenchmarks for {ctx.namespace}::Version.
 */

{includes}
namespace {{

void BM_Version(benchmark::State& state) {{
  for (auto _ : state) {{
    // Mutable lvalue required: const-ref DoNotOptimize is deprecated under -Werror.
    std::string_view version = {ctx.namespace}::Version();
    benchmark::DoNotOptimize(version);
  }}
}}
BENCHMARK(BM_Version);

}}  // namespace
"""
